FROM php:8.1-cli-alpine

RUN apk add --no-cache \
      icu-dev 
 
RUN docker-php-ext-install \
    -j$(nproc) \
    intl \
    pcntl \
    pdo_mysql \
    mysqli 

RUN  apk add --no-cache \
      coreutils \
      autoconf \
      build-base \
      && pecl install xdebug
 

RUN echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.mode=develop,debug" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/xdebug.ini